---
name: fluvial-particle
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - mamba
  - vtk>=9.1
  - poetry
  - pip
  # Production dependencies defined here (as well as in requirements.txt)
  - click
  - h5py
  - numpy
