---
name: fluvial-particle-mpi
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.10
  - h5py=*=mpi_*
  - vtk>=9.1,<9.2
  - pip
  # Production dependencies defined here (as well as in requirements.txt)
  - click
  - numpy
